# Build stage
FROM node:20-alpine as builder

WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
COPY .env.prod .env
RUN npm run build

# Production stage
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]