site_name: 6ix-Resolve Documentation
theme:
  name: material

nav:
  - Accueil: index.md
  - Architecture: architecture.md
  - Business Plan : business_plan.md
  - Backend:
      - API: backend/api.md
      - Base de données: backend/database.md
  - Frontend: frontend.md
  - Tests: tests.md
  - Explication des tests : EXPLICATION_TESTS_LINTER.md