site_name: 6ix-Resolve Documentation
theme:
  name: material

nav:
  - Accueil: index.md
  - Architecture: architecture.md
  - Backend:
      - API: backend/api.md
      - Base de données: backend/database.md
  - Frontend: frontend.md